SGBD_G4_21410_21386/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('mysqlapp/', include('mysqlapp.urls')),
    path('admin/', admin.site.urls),
]

mysqlapp/urls.py
from django.urls import path
from . import views

app_name = 'mysqlapp'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetalhesView.as_view(), name='detalhes'),
    path('<int:pk>/resultados/', views.ResultadosView.as_view(), name='resultados'),
    path('<int:questao_id>/voto/', views.voto, name='voto'),
    path('aluno/1234/', views.aluno1234, name='aluno1234'),
    path('aluno/2345/', views.aluno2345, name='aluno2345'),
    path('aluno/3456/', views.aluno3456, name='aluno3456'),
    path('ultimas5/', views.ultimas5, name='ultimas5'),
    path('participantes5/', views.participantes5, name='participantes5'),
]

mysqlapp/models.py
from django.db import models

class Questao(models.Model):
    questao_texto = models.CharField(max_length=200)
    data_pub = models.DateTimeField('data publicacao')
    def __str__(self):
        return self.questao_texto

class Opcao(models.Model):
    questao = models.ForeignKey(Questao, on_delete=models.CASCADE)
    opcao_texto = models.CharField(max_length=200)
    votos = models.IntegerField(default=0)
    def __str__(self):
        return self.opcao_texto

class Participante(models.Model):
    opcao = models.ForeignKey(Opcao, on_delete=models.CASCADE)
    nome = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    def __str__(self):
        return self.nome

mysqlapp/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.core.exceptions import ValidationError
from django.core.validators import EmailValidator
from django.views import generic

from .models import Questao, Participante, Opcao


class IndexView(generic.ListView):
    template_name = 'mysqlapp/ultimas5.html'


context_object_name = 'lista_ultimas_questoes'


def get_queryset(self):
    return Questao.objects.order_by('-data_pub')[:5]


class DetalhesView(generic.DetailView):
    model = Questao
    template_name = 'mysqlapp/detalhes.html'


class ResultadosView(generic.DetailView):
    model = Questao
    template_name = 'mysqlapp/resultados.html'


def index(request):
    return HttpResponse("Olá, esta é a página inicial de SGBE-MySQL do grupo 4 constituído pelos alunos 21410 e 21386.")


def detalhes(request, questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)
    validator = EmailValidator()
    try:
        validator(request.POST['email'])
    except ValidationError:
        return render(request, 'mysqlapp/detalhes.html',
                      {'questao': questao, 'error_message': "O email introduzido não é válido.", })


def resultados(request, questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)
    return render(request, 'mysqlapp/resultados.html', {'questao': questao})


def voto(request, questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)
    try:
        opcao_escolhida = questao.opcao_set.get(pk=request.POST['opcao'])
    except (KeyError, Opcao.DoesNotExist):
        return render(request, 'mysqlapp/detalhes.html',
                      {'questao': questao, 'error_message': "Não escolheu uma opção.", })
    else:
        participante = Participante(nome=request.POST['nome'], email=request.POST['email'])
        participante.opcao = opcao_escolhida
        participante.save()
        opcao_escolhida.votos += 1
        opcao_escolhida.save()
        return HttpResponseRedirect(reverse('mysqlapp:resultados', args=(questao.id,)))


def aluno(request, participante_id):
    return HttpResponse("A aluna %s chama-se Ana Silva." % participante_id)


def aluno1234(request):
    return HttpResponse("A aluna 1234 chama-se Maria Pereira.")


def aluno2345(request):
    return HttpResponse("O aluno 2345 chama-se Pedro Monteiro.")


def aluno3456(request):
    return HttpResponse("A aluna 3456 chama-se Ana Silva.")


def ultimas5(request):
    lista_ultimas_questoes = Questao.objects.order_by('-data_pub')[:5]
    contexto = {'lista_ultimas_questoes': lista_ultimas_questoes}
    return render(request, 'mysqlapp/ultimas5.html', contexto)


def participantes5(request):
    lista_participantes = Participante.objects.order_by('-id')[:5]
    lista_combinada = []

    for participante in lista_participantes:
        opcao = str(Opcao.objects.filter(id=participante.opcao_id)[0])
        lista_combinada.append(participante.nome + ' votou em ' + opcao)

    print(lista_combinada)
    contexto = {'lista_combinada': lista_combinada}
    return render(request, 'mysqlapp/participantes5.html', contexto)

mysqlapp/templates/mysqlapp/detalhes.html
<h1>{{ questao.questao_texto }}</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{%endif %}
<form action="{% url 'mysqlapp:voto' questao.id %}" method="post">
{% csrf_token %}
{% for opcao in questao.opcao_set.all %}
<input type="radio" name="opcao" id="opcao{{ forloop.counter }}"
value="{{ opcao.id }}">
<label for="opcao{{ forloop.counter }}">{{ opcao.opcao_texto}}</label><br>
{% endfor %}
<label>O seu nome: </label><input type="text"
name="nome" required><br>
<label>O seu email: </label><input type="text"
name="email" required><br>
<input type="submit" value="Voto">
</form>

mysqlapp/templates/mysqlapp/participantes5.html
{% if lista_combinada %}
<ul>
{% for lista in lista_combinada %}
<li style="list-style: none">{{ lista }}</li>
{% endfor %}
</ul>
{% else %}
<p>Não existem participantes.</p>
{% endif %}

mysqlapp/templates/mysqlapp/resultados.html
    <h1>{{ questao.questao_texto }}</h1>
    <ul>
    {% for opcao in questao.opcao_set.all %}
    <li>{{ opcao.opcao_texto }} -- {{ opcao.votos }} voto {{opcao.votos|pluralize }}</li>
    {% endfor %}

    </ul>
    <a href="{% url 'mysqlapp:detalhes' questao.id %}">Responder novamente</a>

mysqlapp/templates/mysqlapp/ultimas5.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'mysqlapp/style.css' %}">
{% if lista_ultimas_questoes %}
<ul>
{% for questao in lista_ultimas_questoes %}
<li><a href="/mysqlapp/{{ questao.id }}/">{{ questao.questao_texto }}</a></li>
{% endfor %}
</ul>
{% else %}
<p>Não existem questões.</p>
{% endif %}